/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Task } from './Task.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TaskService } from './Task.service';
import { TaskController } from './Task.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Task])],
  providers: [TaskService],
  exports: [TaskService],
  controllers: [TaskController],
})
export class TaskModule {}
