/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Assignment } from './Assignment.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AssignmentService } from './Assignment.service';
import { AssignmentController } from './Assignment.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Assignment])],
  providers: [AssignmentService],
  exports: [AssignmentService],
  controllers: [AssignmentController],
})
export class AssignmentModule {}
