/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Assignment, AssignmentCreate } from './dtos/Assignment.dto';
import { AssignmentController } from './Assignment.controller';
import { AssignmentService } from './Assignment.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('AssignmentController', () => {
  let controller: AssignmentController;
  let spyService: AssignmentService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: AssignmentService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [AssignmentController],
      providers: [AssignmentService, ApiServiceProvider],
    }).compile();

    controller = module.get<AssignmentController>(AssignmentController);
    spyService = module.get<AssignmentService>(AssignmentService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call AssignmentController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call AssignmentController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Assignment();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
