import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class ProjectCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  status: string;
}

export class Project {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  status: string;
}
