/**
 * This file generated by Apso.
 */
import { ProjectModule } from './Project/Project.module';
import { TaskModule } from './Task/Task.module';
import { CommentModule } from './Comment/Comment.module';
import { AssignmentModule } from './Assignment/Assignment.module';

export default [ProjectModule, TaskModule, CommentModule, AssignmentModule];
