/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Project } from './Project.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ProjectService } from './Project.service';
import { ProjectController } from './Project.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Project])],
  providers: [ProjectService],
  exports: [ProjectService],
  controllers: [ProjectController],
})
export class ProjectModule {}
