/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Project, ProjectCreate } from './dtos/Project.dto';
import { ProjectController } from './Project.controller';
import { ProjectService } from './Project.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('ProjectController', () => {
  let controller: ProjectController;
  let spyService: ProjectService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: ProjectService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [ProjectController],
      providers: [ProjectService, ApiServiceProvider],
    }).compile();

    controller = module.get<ProjectController>(ProjectController);
    spyService = module.get<ProjectService>(ProjectService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call ProjectController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call ProjectController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Project();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
