import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class CommentCreate {
  @ApiProperty()
  content: string;
}

export class Comment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  content: string;
}
