/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Comment } from './Comment.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CommentService } from './Comment.service';
import { CommentController } from './Comment.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Comment])],
  providers: [CommentService],
  exports: [CommentService],
  controllers: [CommentController],
})
export class CommentModule {}
